-- =============================================================================
-- Schema de pruebas para H2 (MODE=PostgreSQL).
-- Reproduce el modelo definido en src/main/java/.../domain/model/*.java pero
-- mapeando los tipos exclusivos de Postgres (uuid, jsonb, timestamptz) a tipos
-- soportados por H2 (uuid, varchar, timestamp with time zone).
-- =============================================================================

DROP TABLE IF EXISTS subphase_resources;
DROP TABLE IF EXISTS subphases;
DROP TABLE IF EXISTS phases;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS methodologies;
DROP TABLE IF EXISTS users;

CREATE TABLE methodologies (
    id            UUID         PRIMARY KEY,
    slug          VARCHAR(255) NOT NULL UNIQUE,
    name          VARCHAR(255) NOT NULL,
    introduction  CLOB,
    summary       VARCHAR(255),
    status        VARCHAR(255) NOT NULL DEFAULT 'draft',
    version       INTEGER      NOT NULL DEFAULT 1,
    language_code VARCHAR(255) NOT NULL DEFAULT 'es',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE phases (
    id              UUID         PRIMARY KEY,
    methodology_id  UUID         NOT NULL,
    code            VARCHAR(255),
    title           VARCHAR(255) NOT NULL,
    description     CLOB,
    order_index     INTEGER      NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT phases_methodology_id_fkey
        FOREIGN KEY (methodology_id) REFERENCES methodologies(id) ON DELETE CASCADE,
    CONSTRAINT phases_methodology_id_order_index_key
        UNIQUE (methodology_id, order_index)
);

CREATE TABLE subphases (
    id          UUID         PRIMARY KEY,
    phase_id    UUID         NOT NULL,
    code        VARCHAR(255),
    title       VARCHAR(255) NOT NULL,
    content     CLOB,
    order_index INTEGER,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT subphases_phase_id_fkey
        FOREIGN KEY (phase_id) REFERENCES phases(id) ON DELETE CASCADE,
    CONSTRAINT subphases_phase_id_order_index_key
        UNIQUE (phase_id, order_index)
);

CREATE TABLE resources (
    id            UUID         PRIMARY KEY,
    type          VARCHAR(255) NOT NULL,
    title         VARCHAR(255) NOT NULL,
    url           VARCHAR(255) NOT NULL UNIQUE,
    description   VARCHAR(255),
    provider      VARCHAR(255),
    thumbnail_url VARCHAR(255),
    metadata      CLOB         NOT NULL DEFAULT '{}',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE subphase_resources (
    subphase_id UUID    NOT NULL,
    resource_id UUID    NOT NULL,
    order_index INTEGER NOT NULL DEFAULT 1,
    note        VARCHAR(255),
    PRIMARY KEY (subphase_id, resource_id),
    CONSTRAINT subphase_resources_subphase_id_fkey
        FOREIGN KEY (subphase_id) REFERENCES subphases(id) ON DELETE CASCADE,
    CONSTRAINT subphase_resources_resource_id_fkey
        FOREIGN KEY (resource_id) REFERENCES resources(id) ON DELETE CASCADE,
    CONSTRAINT subphase_resources_subphase_id_order_index_key
        UNIQUE (subphase_id, order_index)
);

CREATE TABLE users (
    id       INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(16)  NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);
